server:
  http:
    addr: 0.0.0.0:8200
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9200
    timeout: 1s
  consul:
      address: 127.0.0.1:8500
data:
  database:
    driver: mysql
    source: root:7212@tcp(127.0.0.1:3306)/mirco_stuff?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
